name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make build
      working-directory: ./arm_matrix_example
      run: make build
    - name: make run matrix
      working-directory: ./arm_matrix_example
      run: make run
    - name: make build FIR
      working-directory: ./arm_fir_example
      run: make build
    - name: make run FIR
      working-directory: ./arm_fir_example
      run: make run

