name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name:  build
      working-directory: ./arm_matrix_example
      run: make build
    - name:  run matrix
      working-directory: ./arm_matrix_example
      run: make run


    - name:  build FIR
      working-directory: ./arm_fir_example
      run: make build
    - name:  run FIR
      working-directory: ./arm_fir_example
      run: make run

      
    - name:  build linear_interp  
      working-directory: ./arm_linear_interp_example
      run: make build
    - name:  run linear_interp
      working-directory: ./arm_linear_interp_example
      run: make run

    - name:  build fir in practice
      working-directory: ./gcc_fir_gnuplot
      run: make build
    - name:  run fir in practice
      working-directory: ./gcc_fir_gnuplot
      run: make run

    - name:  build trig
      working-directory: ./arm_sin_cos_example
      run: make build
    - name:  run fir in trig
      working-directory: ./arm_sin_cos_example
      run: make run